[package]
name = "rs-scp"
version = "0.1.2"
edition = "2021"

[dependencies]
ssh = "0.1.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
indicatif = "0.17.8"
copypasta = { version = "0.10.1", features = ["x11"] }
is-terminal = "0.4.13"