name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          #macos-latest,
          windows-latest
        ]

    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache vcpkg on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: C:\vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install SSH on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libssh-dev

      - name: Install SSH on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install libssh
          echo 'export LIBRARY_PATH=$(brew --prefix libssh)/lib:$LIBRARY_PATH' >> $GITHUB_ENV
          echo 'export LD_LIBRARY_PATH=$(brew --prefix libssh)/lib:$LD_LIBRARY_PATH' >> $GITHUB_ENV

      - name: Install SSH on Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "PATH=C:\vcpkg\installed\x64-windows\lib;$env.PATH" | Out-File -FilePath $GITHUB_ENV -Append
          echo "PATH=C:\vcpkg\installed\x64-windows\bin;$env.PATH" | Out-File -FilePath $GITHUB_ENV -Append
          vcpkg install libssh

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Print env
        run: echo ${{ env.PATH }}

      - name: Build
        run: cargo build --release

      - name: Upload Linux binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: target/release/rs-scp

      - name: Upload macOS binary
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: target/release/rs-scp

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: target/release/rs-scp.exe

  create_tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: cargo_version
        run: echo "::set-output name=version::$(grep '^version =' Cargo.toml | sed -E 's/version = "(.*)"/\1/')"

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v${{ steps.cargo_version.outputs.version }}
          git push origin v${{ steps.cargo_version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: [ build, create_tag ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Linux binary
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: target/release

      - name: Download macOS binary
        uses: actions/download-artifact@v3
        with:
          name: macos-binary
          path: target/release

      - name: Download Windows binary
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
          path: target/release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.cargo_version.outputs.version }}
          release_name: Release v${{ steps.cargo_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/rs-scp
          asset_name: rs-scp-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/rs-scp
          asset_name: rs-scp-macos
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/rs-scp.exe
          asset_name: rs-scp-windows.exe
          asset_content_type: application/octet-stream