name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          #macos-latest,
          windows-latest
        ]

    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache vcpkg on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: C:\vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install SSH on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libssh-dev

      - name: Install SSH on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install libssh
          echo 'export LIBRARY_PATH=$(brew --prefix libssh)/lib:$LIBRARY_PATH' >> $GITHUB_ENV
          echo 'export LD_LIBRARY_PATH=$(brew --prefix libssh)/lib:$LD_LIBRARY_PATH' >> $GITHUB_ENV

      - name: Install SSH on Windows
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install libssh
          echo '::add-path::C:\vcpkg\installed\x64-windows\lib' >> $GITHUB_ENV
          echo '::add-path::C:\vcpkg\installed\x64-windows\bin' >> $GITHUB_ENV

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Print env
        run: |
            echo "LIBRARY_PATH: $LIBRARY_PATH"
            echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
            echo "PATH: $PATH"

      - name: Build
        run: cargo build --release

      - name: Upload Linux binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: target/release/rs-scp

      - name: Upload macOS binary
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: target/release/rs-scp

      - name: Upload Windows binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: target/release/rs-scp.exe